### ISSUE TITLE
Password and username 

### ISSUE THREAD

**Issue by many7695** [nightscout/share2nightscout-bridge#35]
What is Dexcom Share2 username, Your Dexcom Share2 password, I’m currently using Dexcom G5, I created a follower entered that name it on username what do I use for the password. I have tried to use my Dexcom username and password, I get an application error

**Comment by bewest** [comment]
Thanks for your participation.  You should be able to test your username and credentials by logging into Dexcom Clarity on the web: https://clarity.dexcom.com for US and https://clarity.dexcom.eu/ for other regions.  We've just released a new version of the bridge, and it works with "new-style" Dexcom accounts.  If you were having issues with a previous version, it might be worth trying again.  If you are hosting on Heroku, redeploying your site should work.  https://nightscout.github.io/update/redeploy
