### ISSUE TITLE
Bridge seems to require alpha-numeric Dexcom passwords

### ISSUE THREAD

**Issue by unsoluble** [nightscout/share2nightscout-bridge#37]
In two separate cases I've worked with so far, users with Dexcom account passwords that were entirely numeric would fail to authenticate their bridge connections. Changing passes to alpha-numeric alternatives fixed the problem.

Not really sure why this would be manifesting, but perhaps something to do with the way the bridge is doing hashing or similar? Anyway, worth investigating.

**Comment by bewest** [comment]
There seem to be a change in encoding rules of some kind for the login process.
https://github.com/nightscout/cgm-remote-monitor/issues/6895
Some experimentation with an account using browser tools should prove instructive as to how Dexcom is encoding these credentials, which we should then match.  A simple guess would be to add `urlencoding`.

**Comment by bewest** [comment]
Thanks for your participation.  We've just released a new version of the bridge, and it works with "new-style" Dexcom accounts.  If you were having issues with a previous version, it might be worth trying again.  If you are hosting on Heroku, redeploying your site should work.  https://nightscout.github.io/update/redeploy/
