### ISSUE TITLE
Connection to Dexcom share does not work

### ISSUE THREAD

**Issue by Josef-A** [nightscout/share2nightscout-bridge#39]
I do not get any data from Dexcom share since 0:47 (CET) of april 9th.

Also reported at:
nightscout/cgm-remote-monitor#5608

xDrip doesn't get any data either, but Dexcom follow works fine.

Let me know if I should send any log files

**Comment by Josef-A** [comment]
If I try with curl as described in #15 I end up with "HTTP/1.1 400 Bad Request" and the text "The server encountered an error processing the request. See server logs for more details."

**Comment by bewest** [comment]
You should be able to test your credentials by using them to sign into Dexcom Clarity on the web.
Try https://clarity.dexcom.com for the US or https://clarity.dexcom.eu for other locations.  Thanks for your participation.  We've just released a new version of the bridge, and it works with "new-style" Dexcom accounts.  If you were having issues with a previous version, it might be worth trying again.  If you are hosting on Heroku, redeploying your site should work.  https://nightscout.github.io/update/redeploy/
