### ISSUE TITLE
Special Characters in Dexcom username issue

### ISSUE THREAD

**Issue by fsallstrom** [nightscout/share2nightscout-bridge#46]
Hi, I just wanted to check if the someone has come up with any other work-around to get dexcom bridge to work with Dexcom accounts having special characters in it, except creating a new dexcom user. I haven't seen any new information about this issue in a while so I expect that is still the only option, but wanted to check just in case. Thanks!

**Comment by tylerwal** [comment]
I need help with this also, I can see that Dexcom will return a session-id with an email username, but it's clearly invalid:
00000000-0000-0000-0000-000000000000

**Comment by tylerwal** [comment]
There is a pull request now that deals with this, great news.

**Comment by fsallstrom** [comment]
> There is a pull request now that deals with this, great news.

Hi. Great news. Does this mean there is a solution to this problem? Did dexcom make any changes on their end? Can you share some info on how you solved it? Thank you in advance.

**Comment by bewest** [comment]
Thanks for your participation.  We've just released a new version of the bridge, and it works with "new-style" Dexcom accounts.  If you were having issues with a previous version, it might be worth trying again.  If you are hosting on Heroku, redeploying your site should work.  https://nightscout.github.io/update/redeploy/
